[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/planner"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/welcome"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/drinks-calculator"
  to = "/public-tools/drinks-calculator/calculator.html"
  status = 200

[[redirects]]
  from = "/drinks-calculator/"
  to = "/public-tools/drinks-calculator/calculator.html"
  status = 200

[[redirects]]
  from = "/drinks-calculator-v2"
  to = "/public-tools/drinks-calculator/calculator-v2.html"
  status = 200

[[redirects]]
  from = "/drinks-calculator-v2/"
  to = "/public-tools/drinks-calculator/calculator-v2.html"
  status = 200
